# Generated by Django 3.1.7 on 2021-02-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank='', max_length=200, verbose_name='Kaynak')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('category', models.CharField(blank='', max_length=200, verbose_name='Kategori')),
                ('subcategory', models.CharField(blank='', max_length=200, verbose_name='Alt Kategori')),
                ('description', models.TextField(blank='', verbose_name='Özet')),
                ('pubDate', models.DateTimeField(blank='', verbose_name='Yayınlanma Tarihi')),
                ('link', models.URLField(blank='', verbose_name='Haber Link')),
                ('thumbnail_url', models.URLField(blank='', verbose_name='Resim Link')),
                ('is_favorite', models.BooleanField(verbose_name='Favori')),
                ('is_select', models.BooleanField(verbose_name='Seç')),
            ],
        ),
    ]
