# Generated by Django 3.1.7 on 2021-02-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank='', null=True, verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_favorite',
            field=models.BooleanField(null=True, verbose_name='Favori'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_admin',
            field=models.BooleanField(null=True, verbose_name='Seç'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank='', null=True, verbose_name='Haber Link'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pubDate',
            field=models.DateTimeField(blank='', null=True, verbose_name='Yayınlanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Kaynak'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subcategory',
            field=models.CharField(blank='', max_length=200, null=True, verbose_name='Alt Kategori'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail_url',
            field=models.URLField(blank='', null=True, verbose_name='Resim Link'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
    ]
