# Generated by Django 3.1.7 on 2021-02-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210227_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(default='', unique=True, verbose_name='Haber Link'),
            preserve_default=False,
        ),
    ]
