# Generated by Django 3.1.7 on 2021-03-01 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_auto_20210227_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ManyToManyField(related_name='users', related_query_name='haber', to=settings.AUTH_USER_MODEL),
        ),
    ]
