# Generated by Django 3.1.7 on 2021-03-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210304_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank='', max_length=200, null=True, verbose_name='Kaynak')),
                ('html_content', models.TextField(blank='', null=True, verbose_name='Html İçerik')),
                ('pubDate', models.DateTimeField(blank='', null=True, verbose_name='Yayınlanma Tarihi')),
            ],
        ),
    ]
