# Generated by Django 3.1.7 on 2021-03-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_company_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_time', models.IntegerField(null=True, verbose_name='Yenilenme Zamanı')),
                ('uptime', models.IntegerField(null=True, verbose_name='Güncel Kalma Süresi')),
            ],
        ),
        migrations.CreateModel(
            name='source_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200, null=True, verbose_name='Kaynak Adı')),
                ('url', models.URLField(verbose_name='Kaynak Url')),
                ('category', models.CharField(max_length=200, null=True, verbose_name='Kategori')),
                ('subcategory', models.CharField(max_length=200, null=True, verbose_name='Alt Kategori')),
                ('time_code', models.IntegerField(null=True, verbose_name='Zaman Farkı')),
                ('special_code', models.IntegerField(null=True, verbose_name='Resim İşleme Kodu')),
                ('active', models.BooleanField(blank=True, null=True, verbose_name='Aktif')),
                ('is_youtube', models.BooleanField(null=True, verbose_name='Youtube')),
                ('refresh_time', models.IntegerField(null=True, verbose_name='Yenilenme Zamanı')),
            ],
        ),
    ]
