# Generated by Django 3.1.7 on 2021-03-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_settings_source_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_news',
            options={'verbose_name': 'Şirket Haberi', 'verbose_name_plural': 'Şirket Haberleri'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Haber', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Ayar', 'verbose_name_plural': 'Ayarlar'},
        ),
        migrations.AlterModelOptions(
            name='source_data',
            options={'verbose_name': 'Kaynak Veri', 'verbose_name_plural': 'Kaynak Verileri'},
        ),
        migrations.AddField(
            model_name='settings',
            name='frequency',
            field=models.IntegerField(default=120, null=True, verbose_name='Çalışma Frekansı'),
        ),
        migrations.AddField(
            model_name='settings',
            name='headers',
            field=models.TextField(default=None, null=True, verbose_name='headers'),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_thread',
            field=models.IntegerField(default=1, null=True, verbose_name='Maksimum İşlemçi Sayısı'),
        ),
        migrations.AddField(
            model_name='settings',
            name='proxies',
            field=models.TextField(default=None, null=True, verbose_name='proxies'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favori'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Seç'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source_data',
            name='url',
            field=models.URLField(unique=True, verbose_name='Kaynak Url'),
        ),
    ]
