# Generated by Django 3.1.7 on 2021-03-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210320_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source_data',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='source_data',
            name='category',
            field=models.CharField(choices=[('Borsa', 'borsa'), ('Gündem', 'gundem'), ('Yaşam', 'yasam'), ('Spor', 'spor'), ('Otomobil', 'otomobil'), ('Teknoloji', 'teknoloji')], max_length=12, null=True, verbose_name='Kategori'),
        ),
    ]
