# Generated by Django 3.1.7 on 2021-03-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210321_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source_data',
            name='special_code',
        ),
    ]
