# Generated by Django 3.1.7 on 2021-03-23 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0012_remove_source_data_special_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='Video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source_data',
            name='is_youtube',
            field=models.BooleanField(null=True, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ManyToManyField(null=True, related_name='selected_news', related_query_name='haber', to=settings.AUTH_USER_MODEL),
        ),
    ]
