# Generated by Django 3.1.7 on 2021-03-23 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0014_auto_20210323_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ManyToManyField(null=True, related_name='selected_news', related_query_name='haber', to=settings.AUTH_USER_MODEL),
        ),
    ]
