# Generated by Django 3.1.7 on 2021-03-23 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0015_auto_20210323_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favori'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Seç'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ManyToManyField(related_name='selected_news', related_query_name='haber', to=settings.AUTH_USER_MODEL),
        ),
    ]
