# Generated by Django 3.1.7 on 2021-03-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20210323_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_favorite',
            field=models.BooleanField(default=False, null=True, verbose_name='Favori'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_admin',
            field=models.BooleanField(default=False, null=True, verbose_name='Seç'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_video',
            field=models.BooleanField(default=False, null=True, verbose_name='Video'),
        ),
    ]
