# Generated by Django 3.1.7 on 2021-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20210323_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Borsa', 'borsa'), ('Yaşam', 'yasam'), ('Spor', 'spor'), ('Otomobil', 'otomobil'), ('Teknoloji', 'teknoloji')], max_length=12, unique=True, verbose_name='Kategori')),
                ('url', models.URLField(unique=True, verbose_name='Kaynak Url')),
                ('javascript_content', models.TextField(null=True, verbose_name='JavaScript')),
                ('html_content', models.TextField(null=True, verbose_name='HTML')),
            ],
        ),
    ]
