# Generated by Django 3.1.7 on 2021-03-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_video_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_data',
            name='category',
            field=models.CharField(choices=[('borsa', 'Borsa'), ('gundem', 'Gündem'), ('yasam', 'Yaşam'), ('spor', 'Spor'), ('otomobil', 'Otomobil'), ('teknoloji', 'Teknoloji')], max_length=20, null=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='video_source',
            name='category',
            field=models.CharField(choices=[('borsa', 'Borsa'), ('yasam', 'Yaşam'), ('spor', 'Spor'), ('otomobil', 'Otomobil'), ('teknoloji', 'Teknoloji')], max_length=12, unique=True, verbose_name='Kategori'),
        ),
    ]
