# Generated by Django 3.1.7 on 2021-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20210324_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_data',
            name='permission_count',
            field=models.IntegerField(default=3, null=True, verbose_name='Kaç Haber Alınabilir'),
        ),
    ]
