# Generated by Django 3.1.7 on 2021-03-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_source_data_permission_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='company_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Şirket Kodu'),
        ),
        migrations.AddField(
            model_name='news',
            name='extra_field',
            field=models.TextField(blank='', null=True, verbose_name='Extra Alan'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_company_news',
            field=models.BooleanField(default=False, null=True, verbose_name='Şirket'),
        ),
    ]
